## Question 1
Write a program using Python that does the following:
- Takes two matrices of any size as the input
- Returns their dot product as the output

Note: You cannot use pre-packaged algorithms for matrix operations for this question.
You can use numpy or pandas to store your data (not for calculations).
Please do the following:

a. Please test the following matrix multiplications using your hand-written code
and report the result:

$ \begin{bmatrix} -4 & -3 & -2 \\ 6 & 0 & -1 \\ 2 & 1 & 3 \end{bmatrix}\begin{bmatrix} 5 & 4 \\ 6 & 7 \\ -4 & -3\end{bmatrix} $

$ \begin{bmatrix} 1 & 0 \\  0 & 1  \end{bmatrix}\begin{bmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8\end{bmatrix} $

b. Compare the result to the packaged dot product numpy.dot. Are they same?

c. Please add your code to your .pdf file and also save it as an .ipynb file

In [15]:
import numpy as np

def create_matrix():
    num_rows_A = int(input("Enter number of rows for matrix A: "))
    num_cols_A = int(input("Enter numer of columns for matrix A: "))

    matrix_A = []

    for i in range(0, num_rows_A):
        matrix_A_row = []
        for j in range(0, num_cols_A):
            ele = int(input("Enter value: "))
            matrix_A_row.append(ele)
        matrix_A.append(matrix_A_row)

    print("MATRIX A")
    print(np.array(np.mat(matrix_A)))

    num_rows_B = int(input("Enter number of rows for matrix B: "))
    num_cols_B = int(input("Enter numer of columns for matrix B: " ))

    matrix_B = []

    for i in range(0, num_rows_B):
        matrix_B_row = []
        for j in range(0, num_cols_B):
            ele = int(input("Enter value: "))
            matrix_B_row.append(ele)
        matrix_B.append(matrix_B_row)

    print("MATRIX B")
    print(np.array(np.mat(matrix_B)))
    
    return matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B



In [16]:
def dot_product(matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B):
    if num_rows_B == num_cols_A:
                matrix_dotprodAB = np.zeros((num_rows_A, num_cols_B))

                for i in range(len(matrix_A)):
                     for j in range(len(matrix_B[0])):
                        for k in range(len(matrix_B)):
                            matrix_dotprodAB[i][j] += matrix_A[i][k] * matrix_B[k][j]
                return matrix_dotprodAB
    else:
        print("The matrices are not compatible")
        return None



#### Part a:

In [17]:
matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B = create_matrix()

Enter number of rows for matrix A: 3
Enter numer of columns for matrix A: 3
Enter value: -4
Enter value: -3
Enter value: -2
Enter value: 6
Enter value: 0
Enter value: -1
Enter value: 2
Enter value: 1
Enter value: 3
MATRIX A
[[-4 -3 -2]
 [ 6  0 -1]
 [ 2  1  3]]
Enter number of rows for matrix B: 3
Enter numer of columns for matrix B: 2
Enter value: 5
Enter value: 4
Enter value: 6
Enter value: 7
Enter value: -4
Enter value: -3
MATRIX B
[[ 5  4]
 [ 6  7]
 [-4 -3]]


In [18]:
dot_product(matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B)

array([[-30., -31.],
       [ 34.,  27.],
       [  4.,   6.]])

In [19]:
dotProd_AB = np.dot(matrix_A, matrix_B)
print(dotProd_AB)

[[-30 -31]
 [ 34  27]
 [  4   6]]


In [20]:
matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B = create_matrix()

Enter number of rows for matrix A: 2
Enter numer of columns for matrix A: 2
Enter value: 1
Enter value: 0
Enter value: 0
Enter value: 1
MATRIX A
[[1 0]
 [0 1]]
Enter number of rows for matrix B: 2
Enter numer of columns for matrix B: 4
Enter value: 1
Enter value: 2
Enter value: 3
Enter value: 4
Enter value: 5
Enter value: 6
Enter value: 7
Enter value: 8
MATRIX B
[[1 2 3 4]
 [5 6 7 8]]


In [21]:
dot_product(matrix_A, matrix_B, num_rows_B, num_cols_A, num_rows_A, num_cols_B)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [22]:
dotProd_AB = np.dot(matrix_A, matrix_B)
print(dotProd_AB)

[[1 2 3 4]
 [5 6 7 8]]


#### Part b:

Yes, the packaged dot product numpy.dot and the handwritten code for matrix multiplication give the same results.

## Question 2

Assume that we have two (2) d-dimensional real vectors x and y. And denote by xi (or yi)
the value in the i-th coordinate of x (or y). Prove or disprove the following statements by
checking non-negativity, definiteness, homogeneity, and triangle inequality.

a. The following distance function is a metric. (5 points)

${L_{1}(x,y)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert$

b. The following distance function is a metric. (5 points)

${L_{2}(x,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$

c. The following distance function is a metric. (10 points)

${L_{2}^2(x,y)} =   {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$



### In order to check whether a distance function is a metric, we need to check for the following properties:



Non-negativity: For all $ x ∈ R^n $, $f(x) ≥ 0 $

Definiteness: f(x) = 0 if x = 0

Homogeneity: For all $ x ∈ R^n, t ∈ R → f(tx) = \lvert t \rvert f(x) $

Triangle inequality: $ d(𝑥,𝑦) ≤ d(𝑥,𝑧) + d(𝑧,𝑦) $ for all points $ 𝑥,𝑦,𝑧 ∈ 𝑋 $

#### Part a:

${L_{1}(x,y)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert$



${\lvert x_{i} - y_{i} \rvert ≥0}$ for all 1 ≤ i ≤ d 

Hence, 

$\sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert ≥0$

The distance function is non-negative.

if ${  x_{i} - y_{i} = 0}$ 

then, ${\lvert x_{i} - y_{i} \rvert = 0}$ for all 1 ≤ i ≤ d 

Hence,

$ \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert = 0 $

The distance function is definite.

${\lvert t . x_{i} - t . y_{i} \rvert = \lvert t \rvert . \lvert x_{i} - y_{i} \rvert}$ for all 1 ≤ i ≤ d 

Hence,

$ \sum \limits _{i=1} ^{d} \lvert t . x_{i} - t . y_{i} \rvert = \sum \limits _{i=1} ^{d} \lvert t \rvert . \lvert x_{i} - y_{i} \rvert = \lvert t \rvert . \sum \limits _{i=1} ^{d}  \lvert x_{i} - y_{i} \rvert $

The distance function is homogenous.


Consider,

${L_{1}(x,y)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert$

${L_{1}(x,z)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - z_{i} \rvert$

${L_{1}(z,y)} =  \sum \limits _{i=1} ^{d} \lvert z_{i} - y_{i} \rvert$

Hence,

${L_{1}(x,y)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert = \sum \limits _{i=1} ^{d} \lvert x_{i} - z_{i}  +   z_{i} - y_{i} \rvert ≤ \sum \limits _{i=1} ^{d} \lvert x_{i} - z_{i} \rvert + \sum \limits _{i=1} ^{d} \lvert z_{i} - y_{i} \rvert$

${L_{1}(x,y)} ≤ L_{1}(x,z) + L_{1}(z,y)$

The distance function satisfies the triangle inequality condition.

The distance function ${L_{1}(x,y)} =  \sum \limits _{i=1} ^{d} \lvert x_{i} - y_{i} \rvert $ is a metric.

#### Part b:

${L_{2}(x,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$

$  {{ (x_{i} - y_{i})}^2 ≥ 0} $ for all 1 ≤ i ≤ d 

$ {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} ≥0$ is a non-negative real function since it is a metric and the square root of any non-negative real number is also a non-negative real number. 

Hence, 

$\sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} ≥0$  is a non-negative real function.


The distance function is non-negative.

if ${  x_{i} - y_{i} = 0}$ 

⇒ ${{(x_{i} - y_{i})}^2 = 0}$ for all 1 ≤ i ≤ d 

⇒ $ {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} = 0$

Hence,

$ \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} = 0$

The distance function is definite.

$ f(x) = \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} $

$ f(t.x) = \sqrt {\sum \limits _{i=1} ^{d} { (t.x_{i} - t.y_{i})}^2} = \sqrt {\sum \limits _{i=1} ^{d} { t^2(x_{i} - y_{i})}^2} =  |t| \sqrt {\sum \limits _{i=1} ^{d} {(x_{i} - y_{i})}^2} = \lvert t \rvert f(x)$ 


The distance function is homogenous.

${L_{2}(x,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} $

${L_{2}(x,z)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - z_{i})}^2} $

${L_{2}(z,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (z_{i} - y_{i})}^2} $

Hence,

${L_{2}(x,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} ≤ \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - z_{i})}^2} + \sqrt {\sum \limits _{i=1} ^{d} { (z_{i} - y_{i})}^2} $

${L_{2}(x,y)} ≤ L_{2}(x,z) + L_{2}(z,y)$

The distance function satisfies the triangle inequality condition.

The distance function ${L_{2}(x,y)} =  \sqrt {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} $ is a metric.

#### Part c:

${L_{2}^2(x,y)} =   {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$

$  { (x_{i} - y_{i})}^2 ≥ 0 $ for all 1 ≤ i ≤ d 

⇒ $ {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} ≥ 0 $ 

⇒ ${L_{2}^2(x,y)} ≥ 0 $

The distance function is non-negative.

if ${  x_{i} - y_{i} = 0} $ 

⇒ ${{(x_{i} - y_{i})}^2 = 0}$ for all 1 ≤ i ≤ d 

⇒ $ {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} = 0$

Hence,

${L_{2}^2(x,y)} = 0 $

The distance function is definite.

$ f(x) =    {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} $

$ f(t.x) =    {\sum \limits _{i=1} ^{d} { (t.x_{i} - t.y_{i})}^2} = {\sum \limits _{i=1} ^{d} { t^2(x_{i} - y_{i})}^2} =  t^2  {\sum \limits _{i=1} ^{d} {(x_{i} - y_{i})}^2} $ 


The distance function is homogenous.

Consider,

${L_{2}^2(x,y)} =  {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2} $

${L_{2}^2(x,z)} =  {\sum \limits _{i=1} ^{d} { (x_{i} - z_{i})}^2}$

${L_{2}^2(z,y)} =  {\sum \limits _{i=1} ^{d} { (z_{i} - y_{i})}^2}$

Hence,

${L_{2}^2(x,z)} + {L_{2}^2(z,y)}$

⇒ $ {\sum \limits _{i=1} ^{d} { (x_{i} - z_{i})}^2} + {\sum \limits _{i=1} ^{d} { (z_{i} - y_{i})}^2} $

⇒ $ {\sum \limits _{i=1} ^{d} ({x_i^2 - 2x_i.z_i + z_i^2 + z_i^2 - 2z_i.y_i + y_i^2})} $

⇒ $ {\sum \limits _{i=1} ^{d} ({x_i^2 + y_i^2 + 2z_i^2 - 2x_i.z_i - 2z_i.y_i })} $

⇒ $ {\sum \limits _{i=1} ^{d} ({x_i^2 + y_i^2 - 2x_i.y_i + 2x_i.y_i + 2z_i^2 - 2x_i.z_i - 2z_i.y_i })} $

⇒ $ {\sum \limits _{i=1} ^{d} ({(x_i - y_i)^2 + 2x_i.y_i + 2z_i^2 - 2x_i.z_i - 2z_i.y_i })} $

⇒ $ {\sum \limits _{i=1} ^{d} ({(x_i - y_i)^2 + 2(z_i^2 + x_i.y_i - x_i.z_i - z_i.y_i )})} $

⇒ $ {\sum \limits _{i=1} ^{d} {(x_i - y_i)^2}} + 2{\sum \limits _{i=1} ^{d} (z_i^2 + x_i.y_i - x_i.z_i - z_i.y_i )} $

Now, consider $ t = 2{\sum \limits _{i=1} ^{d} (z_i^2 + x_i.y_i - x_i.z_i - z_i.y_i )} $

LHS: ${\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$

RHS: ${\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}$ + t

if t = 0, then LHS = RHS

if t > 0, then LHS  < RHS

But,
if t < 0, then LHS > RHS

i.e. if $ 2{\sum \limits _{i=1} ^{d} (z_i^2 + x_i.y_i - x_i.z_i - z_i.y_i )} < 0 $ then ${L_{2}^2(x,y) > L_{2}^2(x,z) + L_{2}^2(z,y)} $

The distance function does not satisfy the triangle inequality condition for all cases.

The distance function ${{L_{2}^2(x,y)} = {\sum \limits _{i=1} ^{d} { (x_{i} - y_{i})}^2}} $ is not a metric.


## Question 3

Calculating by hand, find the characteristic polynomial, eigenvalues and the eigenvectors
of the following matrix:

$$\begin{bmatrix} 4 & 4 & 4 \\ -2 & -3 & -6 \\ 1 & 3 & 6 \end{bmatrix}$$


Let's assume,
$\begin{align}
A = \begin{bmatrix} 4 & 4 & 4 \\ -2 & -3 & -6 \\ 1 & 3 & 6 \end{bmatrix}
\end{align}$



### characteristic polynomial of matrix:



##### step 1:

$ [A] - \lambda . [I] = \begin{bmatrix} 4 & 4 & 4 \\ -2 & -3 & -6 \\ 1 & 3 & 6 \end{bmatrix} - \lambda . \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} = \begin{bmatrix} 4-\lambda & 4 & 4 \\ -2 & -3-\lambda & -6 \\ 1 & 3 & 6-\lambda \end{bmatrix}$

##### step 2:

$ det([A] - \lambda * [I]) = \{(4 - \lambda) * [(-3 - \lambda) * (6 - \lambda) - (-6 * 3)]\} - \{4 * [(-2 * (6 - \lambda)) - (-6 * -1)]\} + \{4 * [(-2 * 3) - (1 * (-3-\lambda))] \}$

$ \{4 * [\lambda^2 - 3\lambda] - \lambda[\lambda^2 - 3\lambda]\} - \{-24 + 8\lambda\} + \{-12 + 4\lambda\} $

##### Answer:

$ -\lambda^3 + 7\lambda^2 - 16\lambda + 12 $


### eigenvalues of matrix:



#### step 1:

The characteristic equation is:

$ -\lambda^3 + 7\lambda^2 - 16\lambda + 12 = 0$


#### step 2:

factorizing the above equation:

$ (\lambda - 2)(-\lambda^2 + 5\lambda - 6) = 0 $

$ (\lambda - 2)(-\lambda^2 + 2\lambda + 3\lambda- 6) = 0 $

$ (\lambda - 2)[-\lambda(\lambda-2) + 3(\lambda - 2)] = 0 $

$ (\lambda - 2)(\lambda - 2)(\lambda -3) = 0 $

$ \lambda = 2, \lambda =3 $



#### Answer:

The eigenvalues are 2 & 3.

### eigenvectors of matrix:



#### When $ \lambda = 2 $,

#### step 1:

⇒ $ \begin{bmatrix} 4-\lambda & 4 & 4 \\ -2 & -3-\lambda & -6 \\ 1 & 3 & 6-\lambda \end{bmatrix}\begin{bmatrix} X \\ Y \\ Z\end{bmatrix}= \begin{bmatrix} 0 \\ 0 \\ 0\end{bmatrix} $

⇒ $ \begin{bmatrix} 2 & 4 & 4 \\ -2 & -5 & -6 \\ 1 & 3 & 4 \end{bmatrix}\begin{bmatrix} X \\ Y \\ Z\end{bmatrix}= \begin{bmatrix} 0 \\ 0 \\ 0\end{bmatrix} $




#### step 2:

Setting X = 1, we get the following equations:

$ 2(1) + 4Y + 4Z = 0 $

$ -2(1) - 5Y - 6Z = 0 $

#### step 3:

⇒ $ [2 + 4Y + 4Z = 0] ------> X 3 $ (eq1)

$ [-2 - 5Y - 6Z = 0] ------> X 2 $  (eq2)

---------------------------------
⇒ $ 12Y + 12Z + 6 = 0 $

$ -10Y - 12Z - 4 = 0 $

---------------------------------
⇒ $ 2Y + 2 = 0 $

⇒ $ Y = -1 $

----------------------------------

Substituting Y = -1 in eq1

⇒ $ 2 + 4(-1) + 4Z = 0 $

⇒ $ 4Z - 2 = 0 $

⇒ $ Z = 1/2 $

#### step 4:

The eigenvector when $\lambda = 2 $ is (1, -1, 1/2)

For convenience, we can scale up by a factor of 2, to get:

(2, -2, 1)

#### When $ \lambda = 3 $,

#### step 1:

⇒ $ \begin{bmatrix} 4-\lambda & 4 & 4 \\ -2 & -3-\lambda & -6 \\ 1 & 3 & 6-\lambda \end{bmatrix}\begin{bmatrix} X \\ Y \\ Z\end{bmatrix}= \begin{bmatrix} 0 \\ 0 \\ 0\end{bmatrix} $

⇒ $ \begin{bmatrix} 1 & 4 & 4 \\ -2 & -6 & -6 \\ 1 & 3 & 3 \end{bmatrix}\begin{bmatrix} X \\ Y \\ Z\end{bmatrix}= \begin{bmatrix} 0 \\ 0 \\ 0\end{bmatrix} $

#### step 2:

Setting X = 1, we get the following equations:

$ 1(1) + 4Y + 4Z = 0 $

$ -2(1) - 6Y - 6Z = 0 $

#### step 3:

⇒ $ [1 + 4Y + 4Z = 0] ------> X 3 $ (eq1)

$ [-2 - 6Y - 6Z = 0] ------> X 2 $  (eq2)

---------------------------------
⇒ $ 12Y + 12Z + 3 = 0 $

$ -12Y - 12Z - 4 = 0 $

---------------------------------
⇒ $ X  ≠ 1$



#### step 4:

Setting Y = 1, we get the following equations:

$ X + 4(1) + 4Z = 0 $

$ -2X - 6(1) - 6Z = 0 $

#### step 5:

⇒ $ X +  4Z + 4 = 0 ------- X2 $ (eq1)

$ -2X - 6Z - 6 = 0 $ (eq2)

---------------------------------

⇒ $ 2X +8Z +8 = 0 $

$ -2X - 6Z - 6 = 0 $

---------------------------------

⇒ $ 2Z + 2 = 0 $

---------------------------------

⇒ $ Z = -1$

#### step 6:

Substituting $ Z = -1 $ in eq1

$ X = 0 $

#### step 7:

The eigenvector when $\lambda = 2 $ is (1, -1, 1/2)

For convenience, we can scale up by a factor of 2, to get:

(0, 1, -1)

#### Answer:

The Eigenvector corresponding to $\lambda = 2$ is $ [2, -2, 1] $

The Eigenvector corresponding to $\lambda = 3$ is $ [0, 1, -1] $


## Question 4

Provide a proof for the following: Let A, B, and C be any n x n matrices:

a. Show that trace(ABC) = trace(CAB) = trace(BCA) (10 points)

b. trace(ABC) = trace(BAC). Provide a proof or a counterexample (10 points)

#### Part a:

Consider the following two matrices,

$ X = \begin{bmatrix} x_{11} & x_{12} & x_{13} & ... & x_{1n} \\ x_{21} & x_{22} & x_{23} & ... & x_{2n} \\ x_{31} & x_{32} & x_{33} & ... & x_{3n} \\ ... & ... & ... & ... & .... \\ x_{n1} & x_{n2} & x_{n3} & ... & x_{nn} \end{bmatrix} $ 

$ Y = \begin{bmatrix} y_{11} & y_{12} & y_{13} & ... & y_{1n} \\ y_{21} & y_{22} & y_{23} & ... & y_{2n} \\ y_{31} & y_{32} & y_{33} & ... & y_{3n} \\ ... & ... & ... & ... & ... \\ y_{n1} & y_{n2} & y_{n3} & ... & y_{nn} \end{bmatrix} $ 

--------------------------

Then, 

$ X.Y = \begin{bmatrix} x_{11}.y_{11} + x_{12}.y_{21} + ... + x_{1n}.y_{n1}  & ... & ... & ... & ... \\ ... & x_{21}.y_{12} + x_{22}.y_{22} + ... + x_{2n}.y_{n2} & ... & ... & ... \\ ... & ... & ... & ... & ... \\ ... & ... & ... & ... & .... \\ ... & ... & ... & ... & x_{n1}.y_{1n} + x_{n2}.y_{2n} + ... + x_{nn}.y_{nn} \end{bmatrix}  $

---------------------------

This means that,

$ Trace(AB) = [x_{11}.y_{11} + x_{12}.y_{21} + ... + x_{1n}.y_{n1}] + [x_{21}.y_{12} + x_{22}.y_{22} + ... + x_{2n}.y_{n2}] + ... + [x_{n1}.y_{1n} + x_{n2}.y_{2n} + ... + x_{nn}.y_{nn}] $

In simpler terms it can be expressed as follows, 

$ Trace(XY) = \sum x_{ij}.y_{ji} $

⇒ $ Trace(XY) = \sum_{i} \sum_{j} x_{ij}.y_{ji} $

Since $ x_{ij}, y_{ij} $ are scalar, 

$ x_{ij}.y_{ij} = y_{ij}.x_{ij} $

Hence,

⇒ $ Trace(XY) = \sum_{i} \sum_{j} y_{ij}.x_{ji} $


⇒ $ Trace(XY) = Trace(YX) $

----------------------------------

Now consider,

$ X = AB $

$ Y = C $

$ Trace(XY) = Trace(YX) $

⇒ $ Trace((AB)C) = Trace(C(AB)) $

⇒ $ Trace(ABC) = Trace(CAB) $

--------------------------------------

Also consider,

$ X = CA $

$ Y = B $

$ Trace(XY) = Trace(YX) $

⇒ $ Trace((CA)B) = Trace(B(AC)) $

⇒ $ Trace(CAB) = Trace(BAC) $

-----------------------------------------

Therefore,

$ Trace(ABC) = Trace(CAB) = Trace(BAC) $

#### Part b:

Let 

$ A = \begin{bmatrix} 3 & 1 \\ 0 & 3\end{bmatrix} $

$ B = \begin{bmatrix} 1 & 2 \\ 2 & 1\end{bmatrix} $

$ C = \begin{bmatrix} 2 & 3 \\ 3 & 0\end{bmatrix} $

$ ABC = \begin{bmatrix} 3 & 1 \\ 0 & 3\end{bmatrix} \begin{bmatrix} 1 & 2 \\ 2 & 1\end{bmatrix}\begin{bmatrix} 2 & 3 \\ 3 & 0\end{bmatrix} = \begin{bmatrix} 5 & 7 \\ 6 & 3\end{bmatrix} \begin{bmatrix} 2 & 3 \\ 3 & 0\end{bmatrix} = \begin{bmatrix} 31 & 15 \\ 21 & 18 \end{bmatrix} $

$ BAC = \begin{bmatrix} 1 & 2 \\ 2 & 1\end{bmatrix}  \begin{bmatrix} 3 & 1 \\ 0 & 3\end{bmatrix} \begin{bmatrix} 2 & 3 \\ 3 & 0\end{bmatrix} = \begin{bmatrix} 3 & 7 \\ 6 & 5\end{bmatrix} \begin{bmatrix} 2 & 3 \\ 3 & 0\end{bmatrix} = \begin{bmatrix} 27 & 9 \\ 27 & 18\end{bmatrix}$

$ Trace(ABC) = 31 + 18 = 49 $

$ Trace(BAC) = 27 + 18 = 45 $

Thus,

$ Trace(ABC) ≠ Trace(BAC) $

## Question 5

Let A and B be n x n matrices with AB = 0.

Each question below is 5 points. Provide a proof or counterexample for each of the
following:

a. BA = 0

b. Either A = 0 or B = 0 (or both)

c. If det(A) = -3, then B = 0

d. There is a vector v ≠ 0 such that BAv = 0

#### Part a:

$ A = \begin{bmatrix} 0 & 1 \\ 0 & 1 \end{bmatrix} $

$ B = \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix} $

$ AB = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix} $

$ BA = \begin{bmatrix} 0 & 2 \\ 0 & 0 \end{bmatrix} $

Hence, the statement if AB = 0 then BA = 0 is False.


#### Part b:

$ A = \begin{bmatrix} 0 & 1 \\ 0 & 1 \end{bmatrix} $

$ B = \begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix} $

$ AB = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix} $

But,

$A ≠ 0$ and $B≠0$

Hence, the statement Either A = 0 or B = 0 (or both) is False.

#### Part c:

##### Method 1:
$ AB = 0 $

⇒ $ det(AB) = 0 $

$ det(AB) = det(A) . det(B) $



Consider, 

$ A = \begin{bmatrix} n_{1} & n_{2} \\ n_{3} & n_{4} \end{bmatrix} $

And, $ det(A) = n_{1}. n_{4} - n_{2}.n_{3} =  -3 $

$ B = \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} $

$ A.B =  \begin{bmatrix} n_{1}b_{11} + n_{2}b_{21} & b_{1}b_{12} + n_{2}b_{22} \\ n_{3}b_{11} + n_{4}b_{21} & n_{3}b_{12} + n_{4}b_{22} \end{bmatrix} $

And, we know that AB=0

So we get the following equations:

$ n_{1}b_{11} + n_{2}b_{21} = 0 $ (eq 1)

$ n_{3}b_{11} + n_{4}b_{21} = 0 $ (eq 2)

$ b_{1}b_{12} + n_{2}b_{22} = 0 $ (eq 3)

$ n_{3}b_{12} + n_{4}b_{22} = 0 $ (eq 4)

Considering eq1 and eq2;

$ n_{1}b_{11} + n_{2}b_{21} = 0  ... [eq1 x n_{3}] $

$ n_{3}b_{11} + n_{4}b_{21} = 0  ... [eq2 x -n_{1}] $

⇒ $ n_{1}n_{3}b_{11} + n_{2}n_{3}b_{21} = 0 $ 

$ - n_{1}n_{3}b_{11} - n_{1}n_{4}b_{21} = 0 $ (eq 2)

Solving the above 2 equations, we get

$ [n_{1}n_{4} - n_{2}n_{3}]b_{21} = 0 $

So, either $ n_{1}n_{4} - n_{2}n_{3} = 0 $ or $ b_{21} = 0 $

But, we know that $ n_{1}n_{4} - n_{2}n_{3} = det(A) = -3 $

Hence, $ b_{21} = 0 $

Similarly, $ b_{11}=0, b_{21}=0, b_{22}=0 $

So if det(A) = -3 then det(B) should be equal to 0.


##### Method 2:

$ AB = 0$

We can assume that $ A^{-1} $ exists since $ det(A) ≠ 0 $

Multiplying both sides by $ A^{-1} $

⇒ $ A.B.A^{-1} = 0.A^{-1} $

⇒ $ B = 0 $

⇒ $ det(B) = 0 $

So if det(A) = -3 then det(B) should be equal to 0.



#### Part d:

There is a vector v ≠ 0 such that BAV = 0

AB = 0

⇒ det(AB) = det(BA) = 0

⇒ BA is not invertible (Since, a matrix is invertible only when it’s product with
non-zero vector is 0).

Hence, there is a vector v ≠ 0 such that BAv = 0